pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Verify Python') {
            steps {
                sh '''
                    python3 --version
                    pip3 --version
                '''
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                    pip3 install --break-system-packages -r requirements.txt
                '''
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    docker build -t python-webapp:1.0 .
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    docker stop flask-demo || true
                    docker rm flask-demo || true

                    docker run -d \
                      --name flask-demo \
                      -p 5000:5000 \
                      python-webapp:1.0
                '''
            }
        }

        stage('Application Test') {
            steps {
                sh '''
                    sleep 10
                    curl http://host.docker.internal:5000
                '''
            }
        }

        stage('AI Deployment Analysis') {
            steps {
                sh '''
echo "Creating Deployment Log..."

cat > deployment.log <<EOF
=========================================
Jenkins AI Deployment Report
=========================================

Project Name: Python-WebApp

Python Version:
$(python3 --version)

Docker Image:
python-webapp:1.0

Container:
flask-demo

Deployment Status:
SUCCESS

Application Test:
PASSED

Generated By:
Jenkins Pipeline
=========================================
EOF

echo ""
echo "========== DEPLOYMENT LOG =========="
cat deployment.log
echo "===================================="

PROMPT=$(cat deployment.log)

echo ""
echo "Sending deployment log to Ollama AI..."
echo ""

curl http://host.docker.internal:11434/api/generate \
-H "Content-Type: application/json" \
-d "{
\"model\":\"smollm2:latest\",
\"prompt\":\"Analyze the following Jenkins deployment log and provide:
1. Deployment Status
2. Deployment Summary
3. Any Issues
4. Recommendations

$PROMPT\",
\"stream\":false
}"

echo ""
echo "AI Analysis Completed."
'''
            }
        }

    }

    post {
        success {
            echo 'Python Application Deployment Successful'
        }

        failure {
            echo 'Deployment Failed'
        }
    }
}
